poolingDelay: 2000
oneSegmentMessageId:
    -21
    -41
    --1
    --1
multiSegmentsPriority1List:
    -21
    -41
    --1
    --1
multiSegmentsPriority2List:
    -72
    -18
    -17
    --1
reverseProcessingMap:
    41:false
    21:false
    18:true
    17:true
    20:false 
    100:false
    5:false
   -1:false
    72:false
    90:false

roundRobinProcessingMap:
   multiSegmentsPriority1List:false
   multiSegmentsPriority2List:true

firstComeFirstServerProcessingMap:
   multiSegmentsPriority1List:false
   multiSegmentsPriority2List:true




